# Generated by Django 5.2.6 on 2025-09-12 17:27

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('who', models.CharField(max_length=200)),
                ('when', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.CharField(default='Genel kontrol', max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Bekliyor'), ('confirmed', 'Onaylandı'), ('done', 'Tamamlandı'), ('canceled', 'İptal')], default='pending', max_length=20)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'ordering': ['-when', '-created_at'],
            },
        ),
    ]
